### PR TITLE
API Expansion

### PR DESCRIPTION
**Pull request by timkpaine**

### CODE REVIEW

**Comment by timkpaine** [comment]
@dahifi just an FYI as some of my order stuff may run into your work. I'm planning on doing Order/Preference/Watchlist builder classes based on the json schemas provided by TD (I've committed the schemas in this).

**Comment by dahifi** [comment]
I've put many hours into creating proper schema docs that can be parsed by QuickType.io. I'll get them committed in a branch so you can check them out. 

Everything to do with Accounts, Instruments, OrderStrategies, Positions, Quotes, and Transactions are already complete. 

Let me make the changes to the other merge request and I'll commit.

**Comment by timkpaine** [comment]
@dahifi I'm less interested in having custom objects come out (e.g. for accounts, instruments, etc) than to have custom objects to go in (e.g. order, preference, watchlist). But we can put everything in the schemas folder and make custom objects coming out if you've already done the work

**Comment by dahifi** [comment]
Here, https://github.com/dahifi/tdameritrade/tree/types

**Comment by dahifi** [comment]
I was working on this months ago cause I was tired of having to use dictionary keys to access the json coming out of the API. Call the to_dict or from_dict methods to parse data in or out. 

I haven't looked at it in a while, most of the time was spent trying to convert Ameritrade's garbage schema into something that's JSON 2.0 compliant and would parse in QuickType.

**Pull request merged**
