### PR TITLE
Automatically refresh token

### PR DESCRIPTION
**Pull request by timkpaine**
Moved from #39 

I added the ability for TDClient to track the access token age and refresh it in time so that the user of the API doesn't have to handle access token regeneration in his or her code. As such, I removed the accessToken argument from the TDClient constructor. The constructor uses the refresh token to request a new access token and track its age.

I also renamed `auth.referesh_token()` to `auth.access_token()`, because the function returns an access token, not a refresh token.

I am happy to work more on this library as I enhance it and clean it up for my own use. It would be good to write actual tests. The test file doesn't really contain tests.

### CODE REVIEW

**Comment by pkout** [comment]
Any chance we could merge this in? I'd like to avoid running my own fork. I think these are good upgrades to the code. The access token automatic refresh particularly is something people will ask for.

**Comment by timkpaine** [comment]
@pkout there are a few changes necessary, it shouldn't require chromedriver to use this library and it shouldn't attempt to auth the first time you use it

**Comment by pkout** [comment]
@timkpaine I agree about the chromedriver, but not sure how we can avoid the authentication on first use. Without an access token, the API call to TD Ameritrade can't be made, so a request to generate the token will be either sent by the user of the library or by the library itself prior to any other API request. Maybe you meant that one should be able to use their own access token if they have one already? If so, we can make it an option via the constructor or a property setter.

**Comment by timkpaine** [comment]
> Maybe you meant that one should be able to use their own access token if they have one already? If so, we can make it an option via the constructor or a property setter.

yep exactly

**Comment by dahifi** [comment]
I'm using the following pattern to use the refresh token instead of calling the authenticate function again and bringing up Chromedriver like I used to: 

```
import os
import tdameritrade as tdameritrade
from tdameritrade import auth as td_auth

refresh_token = os.getenv('AMERITRADE_REFRESH_TOKEN')
client_id = os.getenv('AMERITRADE_CLIENT_ID')
response = td_auth.refresh_token(refresh_token, client_id)
os.environ['ACCESS_TOKEN'] = response['access_token']
account_id = os.getenv('AMERITRADE_ACCOUNT_ID')
tdclient = tdameritrade.TDClient(accountIds=[account_id])
```

I've also refactored a requests session manager into my fork at https://github.com/dahifi/tdameritrade/tree/request_html. It will throw a 401 InvalidAuthToken exception if the request fails, for now we can catch this and refresh manually, but I will work on getting the requestor to call the refresh after I can get a PR through.

**Comment by dahifi** [comment]
Taking a look at this now and trying to merge in the changes from the PR I added yesterday. I really want the auth functions rolled into the new session handler since that's where the response checking should be. Will see what progress I make this weekend.

**Comment by timkpaine** [comment]
#54

**Pull request closed without merging**
