### PR TITLE
added selenium requirement

### PR DESCRIPTION
**Pull request by cng885**
requirements.txt is missing selenium requirement which throws exception when running auth

### CODE REVIEW

**Comment by timkpaine** [comment]
I'd rather not make this a mandatory requirement as its not necessary to use the package.

**Comment by cng885** [comment]
Hmmm okay. I installed via pip and was thrown this error. Not sure how this works without it. 
image

**Comment by timkpaine** [comment]
thats only if you use the auth stuff. the authentication here is just automating a process that can otherwise be done manually. The core of the library doesnt require that

**Comment by cng885** [comment]
> thats only if you use the auth stuff. the authentication here is just automating a process that can otherwise be done manually. The core of the library doesnt require that

Okay. IMO requirements should cover anything that gets installed in the package module, which auth is. I will go ahead and close this though.

**Comment by timkpaine** [comment]
I probably should've done this as separate libraries, the auth stuff is just so annoying to do that I needed it written down. It might make sense to separate `tdameritrade` from `tdameritrade[auth]`

**Comment by cng885** [comment]
> I probably should've done this as separate libraries, the auth stuff is just so annoying to do that I needed it written down. It might make sense to separate `tdameritrade` from `tdameritrade[auth]`

I would definitely not be opposed to that. BTW--do you welcome PR's on this? Starting up a little personal project with this and would be happy to contribute as things come up.

**Comment by timkpaine** [comment]
@cng885 of course

**Pull request closed without merging**
